### ISSUE TITLE
[internal test]: Recalculate button malfunction in simulato

### ISSUE THREAD

**Issue by swywssaid** [tokamak-network/simple-staking-v2#17]
### Can you specify where the bug exists?

Others

### Which device are you seeing the problem on? (can select multiple)

Desktop

### Which OS are you seeing the problem on? (can select multiple)

MacOS

### What browsers are you seeing the problem on? (can select multiple)

Chrome

### What happened?

An error occurs when using the staking simulator.

1. Click on the simulator.
2. Enter the amount of TON, then click the calculate button.
3. Click the recalculate button.
4. When clicking the calculate button again, it does not function properly.

I have attached images for each step.

### Upload any screenshots to aid with explaining the bug.

1. Click on the simulator.
![image](https://github.com/user-attachments/assets/2f3dd14a-260e-4fa2-afb1-a13c80d96cff)

2. Enter the amount of TON, then click the calculate button.
![image](https://github.com/user-attachments/assets/e53a099f-cda6-4ecb-93cc-6b39c8f8a873)

3. Click the recalculate button.
![image](https://github.com/user-attachments/assets/64848feb-9eaa-4d93-9afe-b47201934922)

4. When clicking the calculate button again, it does not function properly.
![image](https://github.com/user-attachments/assets/1d3f783c-4b16-4839-85ed-a3d9ccb9ae47)

**Comment by Julietnacy** [comment]
@cd4761 You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID STA07638
Please see the link below to our dedicated support line:
[Staking Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
