### ISSUE TITLE
[internal test]: Can not connect metamask wallet

### ISSUE THREAD

**Issue by cenwadike** [tokamak-network/simple-staking-v2#21]
### Can you specify where the bug exists?

Others

### Which device are you seeing the problem on? (can select multiple)

Desktop

### Which OS are you seeing the problem on? (can select multiple)

MacOS

### What browsers are you seeing the problem on? (can select multiple)

Chrome

### What happened?

Can not connect metamask wallet with error "Network not supported. Please change to Mainnet." 

I'm on Titan mainnet...I also tried Titan Sepolia and Thanos Sepolia but still had the error

### Upload any screenshots to aid with explaining the bug.

<img width="1412" alt="Screenshot 2024-10-10 at 11 26 41" src="https://github.com/user-attachments/assets/cf6c7d96-3db8-4ebe-b755-cc1a8d9a3fb5">

**Comment by cd4761** [comment]
plz use sepolia network
