### ISSUE TITLE
[internal test]: Not able to connect Metamask wallet

### ISSUE THREAD

**Issue by rishabh-sharma0x00** [tokamak-network/simple-staking-v2#50]
### Can you specify where the bug exists?

Account

### Which device are you seeing the problem on? (can select multiple)

Desktop

### Which OS are you seeing the problem on? (can select multiple)

Others

### What browsers are you seeing the problem on? (can select multiple)

Chrome

### What happened?

Not able to connect with the Metamask wallet. Getting error "Network not supported. Please change to Mainnet". My selected network is Thanos Sepolia. Even if I switch to Titan Sepolia it does not work

![Screenshot from 2024-10-11 14-04-15](https://github.com/user-attachments/assets/c73efa6d-0f6b-44db-a667-263cc9e475d4)

### Upload any screenshots to aid with explaining the bug.

Upload image here

**Comment by cd4761** [comment]
please test on sepolia. not thanos sepolia
