### ISSUE TITLE
[internal test]: Not able to stake on Thanos Sepolia

### ISSUE THREAD

**Issue by rishabh-sharma0x00** [tokamak-network/simple-staking-v2#51]
### Can you specify where the bug exists?

Stake

### Which device are you seeing the problem on? (can select multiple)

Desktop

### Which OS are you seeing the problem on? (can select multiple)

Others

### What browsers are you seeing the problem on? (can select multiple)

Chrome

### What happened?

I was not able to directly connect my wallet to Thanos Sepolia using so I first switched to Ethereum Mainnet & after connecting switched back to Thanos Sepolia. But when I click on the Thanos Sepolia member for staking I don't see an option to do it. It seems restricted.

![Screenshot from 2024-10-11 14-19-12](https://github.com/user-attachments/assets/05c01e19-d7c5-45bf-9b56-a0e39a72ab52)

![Screenshot from 2024-10-11 14-19-55](https://github.com/user-attachments/assets/2c111488-1750-4e18-a98f-1938962b9e26)

### Upload any screenshots to aid with explaining the bug.

Upload image here

**Comment by cd4761** [comment]
please test on sepolia. not thanos sepolia
