### ISSUE TITLE
[internal test]: Actual staked amount & Your staked amount in display are different

### ISSUE THREAD

**Issue by rishabh-sharma0x00** [tokamak-network/simple-staking-v2#53]
### Can you specify where the bug exists?

Stake

### Which device are you seeing the problem on? (can select multiple)

Desktop

### Which OS are you seeing the problem on? (can select multiple)

Others

### What browsers are you seeing the problem on? (can select multiple)

Chrome

### What happened?

I staked a total of 10 TON on Sepolia testnet. After the transaction is successful my Staked TON under that member is shown as 9.99 TON. Not sure if some fees is being deducted or the staked amount being displayed is wrong

![Screenshot from 2024-10-11 14-29-38](https://github.com/user-attachments/assets/c81332f9-09fe-4343-a00d-767acdc0bc5c)

### Upload any screenshots to aid with explaining the bug.

Upload image here

**Comment by cd4761** [comment]
that is contract related issue.

**Comment by Zena-park** [comment]
Thank you @rishabh-sharma0x00.
Staking TON (SWTON) is a token that is allocated compound interest by logic, and when initially staked, an amount smaller than the principal is staked by the calculation logic.
As time passes and compound interest is received, the staked amount will become larger than the principal.
However, the phenomenon of initially being smaller than the principal may seem very strange, but it is the logic of our staking contract.

@suahnkim @cd4761 As the above phenomenon may cause confusion, it is recommended to provide an explanation in the tooltip.

**Comment by Zena-park** [comment]
This is the part of the contract function that retrieves the balance of the staked TON. 
https://github.com/tokamak-network/ton-staking-v2/blob/41afd7f91b4355446c5cdc281584fb835998412e/contracts/stake/tokens/AutoRefactorCoinage.sol#L106-L110
